DROP DATABASE IF EXISTS jazovci;
CREATE DATABASE jazovci;
USE jazovci;
CREATE TABLE potreb(
id INT AUTO_INCREMENT PRIMARY KEY,
ime VARCHAR(255), 
pass VARCHAR(255)
);
INSERT INTO potreb VALUES
(1, "admin", "admin");